import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanstackProviver from "./providers/TanstackProviver";
import Header from "./sections/header/Header";
import Footer from "./sections/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProviver>
          <Header numberOfItems={1} />
          {children} <Footer />
        </TanstackProviver>
      </body>
    </html>
  );
}
